version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_user_password
      MYSQL_DATABASE: bankingapp
    networks:
      - webserver


  spring-boot:
    image: phat1512/spring-boot
    build:
      context: ./spring-boot/
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/bankingapp?useSSL=false&allowPublicKeyRetrieval=true
      DATABASE_USERNAME: banking_user
      DATABASE_PASSWORD: banking_user_password
      PORT: 8080
    networks:
      - webserver
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - mysql


  mongo:
    container_name: mongo
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - webserver


  nodejs:
    image: phat1512/nodejs
    build: ./nodejs
    volumes:
      - ./nodejs:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "3000"
    environment:
      NODE_ENV: development
      DATABASE: mongodb://mongo:27017/local-idurar-erp-crp
      PORT: 3000
    command: sh -c "npm run setup && npm run dev"
    networks:
      - webserver
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - mongo


  nginx:
    container_name: nginx
    image: phat1512/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-boot
      - nodejs
    expose:
      - "1512"
    networks:
      webserver:
        ipv4_address: 172.18.0.100
    volumes:
      - ./ssl-key/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./ssl-key/selfsigned.key:/etc/ssl/private/selfsigned.key
      
      - ./angular/dist:/usr/share/nginx/angular_html
      - ./react/dist/:/usr/share/nginx/react_html

      - ./webserver/angular.conf:/etc/nginx/conf.d/angular.conf
      - ./webserver/react.conf:/etc/nginx/conf.d/react.conf

      - ./webserver/grafana.conf:/etc/nginx/conf.d/grafana.conf
      - ./webserver/prometheus.conf:/etc/nginx/conf.d/prometheus.conf
      - ./webserver/status.conf:/etc/nginx/conf.d/status.conf
      - ./webserver/denied.conf:/etc/nginx/conf.d/denied.conf

      - ~/Documents/nginx:/var/log/nginx
volumes:
  mongodb_data:


networks:
  webserver:
    name: webserver
    external: true
    # ipam:
    #   config:
    #     - subnet: 172.18.0.0/16
    #       gateway: 172.18.0.1
#127.0.0.1 is supposed to be host's address which should be static all the time
# SSL: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout selfsigned.key -out selfsigned.crt